In [64]:
import numpy as np 

In [65]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
array_a[0]

array([1, 2, 3])

In [67]:
array_a[0][1]

np.int64(2)

In [68]:
array_a[0,1]

np.int64(2)

In [69]:
array_a[:,0]

array([1, 4])

## NEGATIVE INDICES

In [70]:
array_b = np.array([1, 2, 3])
array_b[-1]

np.int64(3)

In [71]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
array_a[-1]

array([4, 5, 6])

In [73]:
array_a[1, -1]

np.int64(6)

## ASSIGNING VALUES

In [74]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [76]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [77]:
array_a[:, 0] = 8
array_a

array([[8, 9, 9],
       [8, 5, 6]])

In [78]:
list_a = [8, 7, 8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [8, 5, 6]])

In [79]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [80]:
array_a = np.array([7, 8, 9])
array_a

array([7, 8, 9])

In [81]:
array_b = np.array([[1, 2, 3], [4, 5, 6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
array_a + 2

array([ 9, 10, 11])

In [83]:
array_b - 2


array([[-1,  0,  1],
       [ 2,  3,  4]])

In [84]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [85]:
array_a + array_b[0]

array([ 8, 10, 12])

In [86]:
array_a + array_b[1]

array([11, 13, 15])

In [87]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [88]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

## Data Supported

In [90]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
array_b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.complex64)
array_b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [98]:
array_b = np.array([[1, 2, 3], [4, 0, 6]], dtype=np.bool)
array_b

array([[ True,  True,  True],
       [ True, False,  True]])

In [99]:
array_b = np.array([[1, 2, 3], [4, 0, 6]], dtype=np.str_)
array_b

array([['1', '2', '3'],
       ['4', '0', '6']], dtype='<U1')