In [1]:
import numpy as np

In [13]:
array_empty = np.empty(shape=(2,3))
array_empty

array([[3.47739925e-081, 5.29076027e+174, 1.17071538e-046],
       [1.90058128e-052, 6.11703250e+169, 1.78019082e-306]])

In [6]:
array_0s = np.zeros(shape=(2,3), dtype=np.int16)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [7]:
array_1s = np.ones(shape=(2,3), dtype=np.int16)
array_1s

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [10]:
array_full = np.full(shape=(2,3), fill_value=90)
array_full

array([[90, 90, 90],
       [90, 90, 90]])

## like function

In [11]:
matrix_A = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])
matrix_A

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [14]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[23925768161198147, 32370111954616435, 23362929877516380,
        29555070129143893, 29273895802044528],
       [31525592535793775, 29555310648557682, 28147905699577964,
        32932988893659237, 29273792722501740],
       [31244220638625897, 32369819898151026, 32651548277080177,
        27303583844991077,   137838385430636]])

In [15]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
array_rng = np.arange(stop=30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
array_rng = np.arange(start = 0, stop=30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
array_rng = np.arange(start = 0, stop=30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

## RANDOM GENERATORS

In [22]:
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg

In [26]:
array_RG = gen(pcg())
array_RG.normal(size = [5,5])

array([[ 0.32627806, -0.91515099,  2.68309111, -0.25424901,  0.2086176 ],
       [-2.54072754,  1.55661807,  2.03927544,  0.98352167,  0.69663152],
       [-0.48721225,  2.22165133,  0.71739469,  0.76944631, -0.01922486],
       [ 0.28151156, -0.65967994, -1.27310322, -0.0996441 , -0.19883182],
       [-2.45970373,  0.02594109, -1.54268469, -0.52006118,  0.29592793]])

In [27]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [29]:
array_int_RG = gen(pcg(seed = 365))
array_int_RG.integers(low = 10, high= 100, size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [33]:
array_int_RG = gen(pcg(seed = 365))
array_int_RG.choice([1,2,3,4,5], p = [0.1, 0.1, 0.1, 0.1, 0.6], size=(5,5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

In [34]:
array_RG = gen(pcg(seed = 365))

array_col_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_col_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_col_3 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
array_col_4 = array_RG.exponential(scale = 4, size = (1000))
array_col_5 = array_RG.geometric(p = 0.7, size = (1000))

In [36]:
randon_test_data = np.array([array_col_1, array_col_2, array_col_3, array_col_4, array_col_5]).transpose()
randon_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [37]:
randon_test_data.shape

(1000, 5)

In [38]:
np.savetxt("Random-Test-From-Numpy.csv", randon_test_data, fmt="%s", delimiter=',' )

In [39]:
np.genfromtxt("Random-Test-From-Numpy.csv", delimiter=',')

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])