In [12]:
import numpy as np

In [13]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [14]:
np.mean(matrix_A)

np.float64(3.4)

In [15]:
np.mean(matrix_A[0])

np.float64(1.0)

In [16]:
np.mean(matrix_A[:,0])

np.float64(2.6666666666666665)

In [17]:
np.mean(matrix_A, axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [18]:
np.mean(matrix_A, axis=1)

array([1. , 5.2, 4. ])

In [19]:
np.sqrt(matrix_A)

array([[1.        , 0.        , 0.        , 1.73205081, 1.        ],
       [1.73205081, 2.44948974, 2.44948974, 1.41421356, 3.        ],
       [2.        , 2.23606798, 1.73205081, 2.82842712, 0.        ]])

In [20]:
np.mean(matrix_A, axis=1, dtype=np.int64)

array([1, 5, 4])

## MAX AND MIN

In [21]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [23]:
np.min(matrix_A[1])

np.int64(2)

In [24]:
np.amin(matrix_A)

np.int64(0)

In [26]:
np.minimum(matrix_A[1], matrix_A[2])

array([3, 5, 3, 2, 0])

In [27]:
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [28]:
np.max(matrix_A)

np.int64(9)

In [29]:
np.amax(matrix_A)

np.int64(9)

In [30]:
np.maximum.reduce(matrix_A)

array([4, 6, 6, 8, 9])