# NumPy DataTypes

In [1]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [2]:
array_hw_1 = np.array([1, 2, 3, 4, 5, 6, 7 ,8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [3]:
type(array_hw_1)

numpy.ndarray

In [4]:
array_hw_1.shape

(8,)

In [9]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [8]:
array_hw_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [10]:
type(array_hw_2)

numpy.ndarray

In [11]:
array_hw_2.shape

(2, 4)

In [12]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [13]:
array_hw_3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
array_hw_3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

### 6. Find its type, shape and size. 


In [14]:
type(array_hw_3)

numpy.ndarray

In [16]:
array_hw_3.shape

(1, 2, 4)

In [17]:
array_hw_3.size

8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [18]:
list_hw_1 = ([[1, 2, 3, 4], [5, 6, 7, 8]])
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [19]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [20]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [21]:
type(list_hw_1)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [24]:
array_hw_4 = np.array(list_hw_1)
array_hw_4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [27]:
list_sum = list_hw_1[0] + list_hw_1[1]
list_sum

[1, 2, 3, 4, 5, 6, 7, 8]

In [28]:
array_sum = array_hw_4[0] + array_hw_4[1]
array_sum

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [29]:
np.sqrt(array_sum)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [30]:
np.sqrt(list_sum)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

In [33]:
lending_co = np.genfromtxt('Lending-Company-Total-Price.csv', 
                           delimiter=",",
                           dtype=np.str_)
lending_co

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2', '16600'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600'],
       ...,
       ['413', 'id_413', 'Product B', ..., 'Location 135', 'Region 1',
        '16600'],
       ['414', 'id_414', 'Product C', ..., 'Location 200', 'Region 6',
        '15600'],
       ['415', 'id_415', 'Product A', ..., 'Location 8', 'Region 2',
        '22250']], dtype='<U14')

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [39]:
lending_co = np.genfromtxt('Lending-Company-Total-Price.csv', 
                           delimiter=",",
                           skip_header= 1,
                           usecols= (0, -1),
                           dtype= None
                           )
lending_co

array([[    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,    -1],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   43, 19250],
       [   

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [40]:
lending_co = np.genfromtxt('Lending-Company-Total-Price.csv', 
                           delimiter=",",
                           skip_header= 1,
                           dtype= None
                           )
lending_co

array([(  1, 'id_1', 'Product B', 'Male', 'Location 2', 'Region 2', 16600),
       (  2, 'id_2', 'Product B', 'Male', 'Location 3', '', 16600),
       (  3, 'id_3', 'Product C', 'Female', 'Location 5', 'Region 5', 15600),
       (  4, 'id_4', 'Product B', 'Male', 'Location 6', 'Region 1', 16600),
       (  5, 'id_5', 'Product D', 'Female', 'Location 7', 'Region 2', 20250),
       (  6, 'id_6', 'Product B', 'Female', 'Location 10', 'Region 2',    -1),
       (  7, 'id_7', 'Product A', 'Male', 'Location 11', 'Region 3', 20250),
       (  8, 'id_8', 'Product B', 'Male', 'Location 12', 'Region 6', 16600),
       (  9, 'id_9', 'Product A', 'Female', 'Location 3', 'Region 3', 22250),
       ( 10, 'id_10', 'Product A', 'Female', 'Location 13', 'Region 6', 20250),
       ( 11, 'id_11', 'Product B', 'Female', 'Location 15', 'Region 2', 16600),
       ( 12, 'id_12', 'Product D', 'Female', 'Location 16', 'Region 1', 20250),
       ( 13, 'id_13', 'Product B', 'Male', 'Location 17', 'Region 3', 166