## Importing Data with NumPy

In [1]:
import numpy as np

### np.loadtxt() vs np.genfromtxt()

In [5]:
file_name = 'Lending-Company-Numeric-Data.csv'
lending_co_numeric_1 = np.loadtxt(file_name, delimiter=',')
lending_co_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [6]:
lending_co_numeric_2 = np.genfromtxt(file_name, delimiter=',')
lending_co_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [9]:
file_name = 'Lending-Company-Numeric-Data-NAN.csv'
lending_co_numeric_NAN = np.loadtxt(file_name, delimiter = ';', dtype='str')
lending_co_numeric_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [10]:
lending_co_numeric_NAN = np.genfromtxt(file_name, delimiter = ';')
lending_co_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### Partial Cleaning While Importing

In [12]:
lending_co_numeric_NAN = np.genfromtxt(file_name, 
                                       delimiter = ';',
                                       skip_footer=2,
                                       skip_header=2)
lending_co_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [14]:
lending_co_numeric_c1, lending_co_numeric_c5, lending_co_numeric_c2 = np.genfromtxt(file_name, 
                                       delimiter = ';',
                                       usecols=(1, 5, 2),
                                       unpack=True)
print(lending_co_numeric_c5)
print(lending_co_numeric_c2)
print(lending_co_numeric_c1)

[13621. 15041. 15340. ... 16600. 15600. 16600.]
[365. 365. 365. ... 365. 365. 365.]
[40. 40. 40. ... 40. 40. 40.]
