# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [ ]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt

#pip install numpy --upgrade

### 2. Install/Upgrade another package (e.g. Pandas) 

In [3]:
# pip install numpy

### 3. Import NumPy as <i> np </i>

In [55]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [ ]:
array_hw_1 = np.array([4, 5, 7, 10])

### 5. Display the new array on screen

In [26]:
array_hw_1

array([ 4,  5,  7, 10])

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [29]:
array_hw_2 = np.array([[4, 5], [7, 10]])

In [30]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [36]:
np.mean(array_hw_1)

np.float64(6.5)

In [35]:
np.mean(array_hw_2)

np.float64(6.5)

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [41]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

In [42]:
np.mean(array_hw_2, axis = 1)

array([4.5, 8.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [43]:
np.mean(array_hw_2, axis = 0)

array([5.5, 7.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [62]:
np.mean(array_hw_1, axis = 0, dtype = int)

np.int64(6)

In [66]:
np.mean(array_hw_2, axis = 1, dtype = int)

array([4, 8])

In [67]:
np.mean(array_hw_2, axis = 0, dtype = int)

array([5, 7])