In [1]:
import pandas as pd 
import numpy as np

In [3]:
price_per_category = pd.Series({'Product A' : 22250,
                                'Product B' : 16600,
                                'Product C' : 15600
})
price_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [4]:
price_per_category.values

array([22250, 16600, 15600])

In [5]:
type(price_per_category.values)

numpy.ndarray

In [6]:
price_per_category.array

<NumpyExtensionArray>
[np.int64(22250), np.int64(16600), np.int64(15600)]
Length: 3, dtype: int64

In [7]:
type(price_per_category.array)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [8]:
price_per_category.to_numpy()

array([22250, 16600, 15600])

In [9]:
type(price_per_category.to_numpy())

numpy.ndarray

In [10]:
test_array = price_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [14]:
type(test_array[0])

numpy.float64