In [16]:
import numpy as np

In [17]:
array_a = np.array([1, 2, 3])
print(array_a)

[1 2 3]


In [18]:
type(array_a)

numpy.ndarray

In [19]:
array_a.shape

(3,)

In [20]:
array_b = np.array([[7, 8, 9], [10, 11, 12]])
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [21]:
array_b.shape

(2, 3)

In [22]:
array_c = np.array(13)

In [23]:
type(array_c)

numpy.ndarray

In [24]:
array_c

array(13)

In [25]:
array_d = np.array([15])
array_d

array([15])

In [26]:
type(array_d)

numpy.ndarray

In [27]:
array_d.shape

(1,)

## LIST vs ARRAY

In [28]:
list_a = [[1, 2, 3], [4, 5, 6]]

In [29]:
len(list_a)

2

In [31]:
new_array_a = np.array(list_a)

In [32]:
type(list_a)

list

In [36]:
type(new_array_a)

numpy.ndarray

In [37]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [38]:
print(new_array_a)

[[1 2 3]
 [4 5 6]]


In [39]:
new_array_a.shape

(2, 3)

In [41]:
len(list_a[0])

3

In [42]:
list_b = list_a[0] + list_a[1]
new_array_b = new_array_a[0] + new_array_a[1]

In [43]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [44]:
print(new_array_b)

[5 7 9]


In [46]:
import math
array_e = math.sqrt(new_array_a[1,0])
print(array_e)

2.0
