In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [19]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

## STEPWISE

In [20]:
matrix_b = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
matrix_b[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [25]:
matrix_b[::2,::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [29]:
matrix_b[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [32]:
matrix_b[-1::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])