In [2]:
import numpy as np

In [3]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [6]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

## STEPWISE

In [7]:
matrix_b = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [8]:
matrix_b[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [9]:
matrix_b[::2,::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [10]:
matrix_b[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [11]:
matrix_b[-1::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [12]:
matrix_c = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [13]:
matrix_c[:,0]

array([1, 3, 4])

In [14]:
matrix_c[:,0] > 2

array([False,  True,  True])

In [15]:
matrix_c[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [ ]:
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [18]:
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]

array([2, 0, 4, 4, 0])

## Dimensions and Squeeze

In [20]:
matrix_d = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_d

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
type(matrix_d[0,0])

numpy.int64

In [22]:
type(matrix_d[0,0:1])

numpy.ndarray

In [23]:
matrix_d[0,0:1]

array([1])

In [24]:
type(matrix_d[0:1,0:1])

numpy.ndarray

In [25]:
matrix_d[0:1,0:1]

array([[1]])

In [26]:
matrix_d[0:1,0:1].squeeze()

array(1)

In [27]:
np.squeeze(matrix_d[0:1,0:1])

array(1)

In [30]:
print(matrix_d[0,0].shape)
print(matrix_d[0,0:1].shape)
print(matrix_d[0:1,0:1].shape)

()
(1,)
(1, 1)


In [31]:
print(matrix_d[0,0].squeeze().shape)
print(matrix_d[0,0:1].squeeze().shape)
print(matrix_d[0:1,0:1].squeeze().shape)

()
()
()
